# This is a basic workflow to help you get started with Actions

name: CI-Linux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    # set up conda
    - name: Setup conda
      uses: s-weigand/setup-conda@v1.0.5
      with:
        python-version: '3.10'

    - name: Install
      run: |
        ls -al
        pwd
        #git clone --recurse-submodules https://github.com/zhangrengang/Centromics
        #cd Centromics
        # install
        #git pull --recurse-submodules
        git clone https://github.com/zhangrengang/REPcluster
        conda env create -f Centromics.yaml
        export PATH=/usr/share/miniconda/envs/RepCent/bin:$PATH
        ls -al REPcluster/
        ./install.sh
    
    - name: Install via mamba
      run: |
        conda install mamba -c conda-forge
        which mamba
        mamba env create -h
        mamba env create --force -f Centromics.yaml
    - name: Test
      run: |
        ls -al
        pwd
